window.PERSONAL_MOVIE_FEED = [
  { tmdbId: "1242011", title: "Together", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "820609", title: "No One Will Save You", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "4233", title: "Scream 2", ownedPhysical: true, physicalNote: "Bluray" },
  { tmdbId: "214", title: "Saw 3", ownedPhysical: true, physicalNote: "Bluray" },
  { tmdbId: "663", title: "Saw 4", ownedPhysical: true, physicalNote: "Bluray" },
  { tmdbId: "70160", title: "the Hunger Games", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "766", title: "Army of Darkness", ownedPhysical: true, physicalNote: "Bluray" },
  { tmdbId: "819876", title: "Crimes of the Future", ownedPhysical: true, physicalNote: "Bluray" },
  { tmdbId: "948549", title: "Love Lies Bleeding", ownedPhysical: true, physicalNote: "Bluray" },
  { tmdbId: "522", title: "Ed Wood", ownedPhysical: true, physicalNote: "Bluray" },
  { tmdbId: "1054867", title: "One Battle After Another", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "924", title: "Dawn of the Dead", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "579974", title: "RRR", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "12429", title: "Ponyo", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "2745", title: "Aladdin", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "13183", title: "Watchmen", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "419430", title: "Get Out", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "7978", title: "Wolf Man (2010)", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "315011", title: "Shin Godzilla", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "823464", title: "Godzilla x Kong", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "671", title: "Harry Potter and the Sorcerer's Stone", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "1175174", title: "Fackam Hall", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "1366", title: "Rocky", ownedPhysical: false, physicalNote: "" },
  { tmdbId: "4638", title: "Hot Fuzz", ownedPhysical: true, physicalNote: "Bluray" },
  { tmdbId: "839033", title: "The Lord of the Rings: The War of the Rohirrim", ownedPhysical: false, physicalNote: "" }
];
